package  com.altioracorp.ordenes.model;

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Articulo generated by hbm2java
 */
@Entity
@Table(name = "articulo", catalog = "prueba")
public class Articulo implements java.io.Serializable {

	private int idarticulo;
	private String nombre;
	private String codigo;
	private BigDecimal preciounitario;
	private Set<Detalleorden> detalleordens = new HashSet<Detalleorden>(0);

	public Articulo() {
	}

	public Articulo(int idarticulo) {
		this.idarticulo = idarticulo;
	}

	public Articulo(int idarticulo, String nombre, String codigo, BigDecimal preciounitario,
			Set<Detalleorden> detalleordens) {
		this.idarticulo = idarticulo;
		this.nombre = nombre;
		this.codigo = codigo;
		this.preciounitario = preciounitario;
		this.detalleordens = detalleordens;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "idarticulo", unique = true, nullable = false)
	public int getIdarticulo() {
		return this.idarticulo;
	}

	public void setIdarticulo(int idarticulo) {
		this.idarticulo = idarticulo;
	}

	@Column(name = "nombre", length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "codigo", length = 100)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "preciounitario")
	public BigDecimal getPreciounitario() {
		return this.preciounitario;
	}

	public void setPreciounitario(BigDecimal preciounitario) {
		this.preciounitario = preciounitario;
	}

//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "articulo")
//	public Set<Detalleorden> getDetalleordens() {
//		return this.detalleordens;
//	}
//
//	public void setDetalleordens(Set<Detalleorden> detalleordens) {
//		this.detalleordens = detalleordens;
//	}

}
