package  com.altioracorp.ordenes.model;
// Generated 06/04/2021 22:55:39 by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cliente generated by hbm2java
 */
@Entity
@Table(name = "cliente", catalog = "prueba")
public class Cliente implements java.io.Serializable {

	private int idcliente;
	private String nombre;
	private String apellido;
	private String identificacion;
	
	private Set<Orden> ordens = new HashSet<Orden>(0);

	public Cliente() {
	}

	public Cliente(int idcliente) {
		this.idcliente = idcliente;
	}

	public Cliente(int idcliente, String nombre, String apellido, String identificacion, Set<Orden> ordens) {
		this.idcliente = idcliente;
		this.nombre = nombre;
		this.apellido = apellido;
		this.identificacion=identificacion;
		this.ordens = ordens;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "idcliente", unique = true, nullable = false)
	public int getIdcliente() {
		return this.idcliente;
	}

	public void setIdcliente(int idcliente) {
		this.idcliente = idcliente;
	}

	@Column(name = "nombre", length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "apellido", length = 50)
	public String getApellido() {
		return this.apellido;
	}

	public void setApellido(String apellido) {
		this.apellido = apellido;
	}
	
	@Column(name = "identificacion", length = 10)
	public String getIdentificacion() {
		return identificacion;
	}

	public void setIdentificacion(String identificacion) {
		this.identificacion = identificacion;
	}

//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cliente")
//	public Set<Orden> getOrdens() {
//		return this.ordens;
//	}
//
//	public void setOrdens(Set<Orden> ordens) {
//		this.ordens = ordens;
//	}

}
