package  com.altioracorp.ordenes.model;
// Generated 06/04/2021 22:55:39 by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Detalleorden generated by hbm2java
 */
@Entity
@Table(name = "detalleorden", catalog = "prueba")
public class Detalleorden implements java.io.Serializable {

	private Integer iddetalle;
	private Orden orden;
	private Articulo articulo;

	public Detalleorden() {
	}

	public Detalleorden(Orden orden, Articulo articulo) {
		this.orden = orden;
		this.articulo = articulo;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "iddetalle", unique = true, nullable = false)
	public Integer getIddetalle() {
		return this.iddetalle;
	}

	public void setIddetalle(Integer iddetalle) {
		this.iddetalle = iddetalle;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "idorden")
	public Orden getOrden() {
		return this.orden;
	}

	public void setOrden(Orden orden) {
		this.orden = orden;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "idarticulo")
	public Articulo getArticulo() {
		return this.articulo;
	}

	public void setArticulo(Articulo articulo) {
		this.articulo = articulo;
	}

}
