package  com.altioracorp.ordenes.model;
// Generated 06/04/2021 22:55:39 by Hibernate Tools 3.5.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Orden generated by hbm2java
 */
@Entity
@Table(name = "orden", catalog = "prueba")
public class Orden implements java.io.Serializable {

	private Integer idorden;
	private Cliente cliente;
	private Date fecha;
	private Set<Detalleorden> detalleordens = new HashSet<Detalleorden>(0);

	public Orden() {
	}

	public Orden(Cliente cliente, Date fecha, Set<Detalleorden> detalleordens) {
		this.cliente = cliente;
		this.fecha = fecha;
		this.detalleordens = detalleordens;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "idorden", unique = true, nullable = false)
	public Integer getIdorden() {
		return this.idorden;
	}

	public void setIdorden(Integer idorden) {
		this.idorden = idorden;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "idcliente")
	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha", length = 19)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orden")
//	public Set<Detalleorden> getDetalleordens() {
//		return this.detalleordens;
//	}
//
//	public void setDetalleordens(Set<Detalleorden> detalleordens) {
//		this.detalleordens = detalleordens;
//	}

}
